/* eslint-disable no-param-reassign */
/** Element Style */

module.exports = {
	Badge: require("./Badge"),
	Body: require("./Body"),
	Button: require("./Button"),
	Card: require("./Card"),
	CardItem: require("./CardItem"),
	Container: require("./Container"),
	Content: require("./Content"),
	CheckBox: require("./CheckBox"),
	Fab: require("./Fab"),
	Form: require("./Form"),
	Footer: require("./Footer"),
	FooterTab: require("./FooterTab"),
	H1: require("./H1"),
	H2: require("./H2"),
	H3: require("./H3"),
	Header: require("./Header"),
	InputGroup: require("./InputGroup"),
	Item: require("./Item"),
	Icon: require("./Icon"),
	Input: require("./Input"),
	Label: require("./Label"),
	Left: require("./Left"),
	ListItem: require("./ListItem"),
	Picker: require("./Picker"),
	Radio: require("./Radio"),
	Right: require("./Right"),
	Segment: require("./Segment"),
	Separator: require("./Separator"),
	Spinner: require("./Spinner"),
	Subtitle: require("./Subtitle"),
	SwipeRow: require("./SwipeRow"),
	Switch: require("./Switch"),
	Textarea: require("./Textarea"),
	Text: require("./Text"),
	Thumbnail: require("./Thumbnail"),
	Title: require("./Title"),
	Toast: require("./Toast"),
	Tab: require("./Tab"),
	TabBar: require("./TabBar"),
	TabContainer: require("./TabContainer"),
	TabHeading: require("./TabHeading"),
	View: require("./View"),
}
