const { key } = require("lodash")
const { Col, Row, Grid } = require("react-native-easy-grid")

module.exports = {
	BorderButton: require("./BorderButton"),
	DataPicker: require("./DataPicker"),
	DatePicker: require("./DatePicker"),
	HIcon: require("./HIcon"),
	HLine: require("./HLine"),
	Html: require("./Html"),
	OverlappedIcon: require("./OverlappedIcon"),
	InputBar: require("./InputBar"),
	List: require("./List"),
	ListItem: require("./ListItem"),
	LocalImage: require("./LocalImage"),
	RemoteImage: require("./RemoteImage"),
	TitleBar: require("./TitleBar"),
	VLine: require("./VLine"),

	keys: key,
	Col,
	Row,
	Grid,

	Accordion: require("./Accordion"),
	ActionSheet: require("./ActionSheet"),
	Badge: require("./Badge"),
	Body: require("./Body"),
	Button: require("./Button"),
	Card: require("./Card"),
	CardItem: require("./CardItem"),
	CheckBox: require("./Checkbox"),
	Container: require("./Container"),
	Content: require("./Content"),
	DatePicker: require("./DatePicker"),
	DeckSwiper: require("./DeckSwiper"),
	DefaultTabBar: require("./Tabs"),
	Drawer: require("./Drawer"),
	Fab: require("./Fab"),
	Footer: require("./Footer"),
	FooterTab: require("./FooterTab"),
	Form: require("./Form"),
	H1: require("./H1"),
	H2: require("./H2"),
	H3: require("./H3"),
	Header: require("./Header"),
	Icon: require("./Icon"),
	InputGroup: require("./InputGroup"),
	Input: require("./Input"),
	Item: require("./Item"),

	Label: require("./Label"),
	Left: require("./Left"),
	List: require("./List"),
	ListItem: require("./ListItem"),

	Picker: require("./Picker"),
	Radio: require("./Radio"),
	Right: require("./Right"),
	Root: require("./Root"),
	Tabs: require("./Tabs"),
	ScrollableTab: require("./Tabs"),
	Segment: require("./Segment"),
	Separator: require("./Separator"),
	Spinner: require("./Spinner"),
	Subtitle: require("./Subtitle"),
	SwipeRow: require("./SwipeRow"),
	Switch: require("./Switch"),
	TabHeading: require("./TabHeading"),
	TabContainer: require("./TabContainer"),
	Tab: require("./Tab"),
	Text: require("./Text"),
	Textarea: require("./Textarea"),
	Thumbnail: require("./Thumbnail"),
	Title: require("./Title"),
	ToastContainer: require("./ToastContainer"),
	View: require("./View"),
}
